services:

  postgres:
    image: postgres:17-alpine
    container_name: stockflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: stockflow
      POSTGRES_USER: stockflow
      POSTGRES_PASSWORD: stockflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stockflow

  mailpit:
    image: axllent/mailpit:latest
    container_name: stockflow-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - stockflow

volumes:
  postgres_data:

networks:
  stockflow:
    driver: bridge